openapi: 3.0.1
info:
  title: payloadtrnsformer
  description: API Definition of payloadtrnsformer
  version: 1.0.0
servers:
- url: http://localhost:8290/payloadtrnsformer
paths:
  /:
    get:
      responses:
        default:
          description: Default response
